import "./globals.css";
import { Nunito } from "@next/font/google";

export const metadata = {
  title: "Tai Chi - Qi Gong - Arcueil",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Nunito&display=swap"
          rel="stylesheet"
        /> */}
      </head>
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
